version: "3.9"

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: security_api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./api:/app/api
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL=llama3.2
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - RISK_THRESHOLD_BLOCK=0.7
      - RISK_THRESHOLD_SANITIZE=0.4
    depends_on:
      - mlflow
    restart: on-failure

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: security_dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./dashboard:/app/dashboard
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    restart: on-failure

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.13.0
    container_name: security_mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri /mlruns
    restart: on-failure